version: "3.8"

services:
  ticket-bot-mysql:
    image: mysql:8
    hostname: ticket-bot-mysql
    volumes: 
      - ticket-bot-mysql:/var/lib/mysql
    networks:
      - ticket-bot
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=discord-ticket
    restart: unless-stopped
  
  ticket-bot:
    image: discord-ticket-v4
    tty: true
    stdin_open: true
    hostname: ticket-bot
    ports: 
      - 8080:8080
      - 8888:8888
    volumes:
      - ticket-bot:/opt/bot/user
    networks:
      - ticket-bot
    depends_on:
      - ticket-bot-mysql
    environment:
      - DISCORD_TOKEN=TOKEN
      - DB_PROVIDER=mysql
      - DB_CONNECTION_URL=mysql://root:$MYSQL_ROOT_PASSWORD@MYSQL_HOSTNAME:3306/discord-ticket
      - ENCRYPTION_KEY=key
      - HTTP_EXTERNAL=http://localhost:8080
      - HTTP_BIND=8080
      - SETTINGS_BIND=8888

    restart: unless-stopped

networks:
  ticket-bot:

volumes:
  ticket-bot-mysql:
  ticket-bot: