version: "3.8"

services:
  bot:
    image: ticket-v3-test
    restart: unless-stopped
    volumes:
      - ticket-bot-v3:/opt/tickets
    environment:
      - DB_TYPE=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=tickets
      - DB_USER=tickets
      - DB_PASS=tickets
      - DB_TABLE_PREFIX=dsctickets_
      - "DISCORD_TOKEN=TOKEN"
    depends_on:
      - db

  db:
    image: mysql:8
    restart: unless-stopped
    environment:
      - "MYSQL_DATABASE=tickets"
      - "MYSQL_USER=tickets"
      - "MYSQL_PASSWORD=tickets"
      - "MYSQL_RANDOM_ROOT_PASSWORD=yes"
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
  ticket-bot-v3:
