version: "3.8"

services:
  ticket-bot-mysql:
    image: mysql:8
    hostname: ticket-bot-mysql
    volumes: 
      - ticket-bot-mysql:/var/lib/mysql
    networks:
      - ticket-bot
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=
    restart: unless-stopped
  
  ticket-bot:
    image: tickets-bot:v4
    tty: true
    stdin_open: true
    hostname: ticket-bot
    volumes:
      - ticket-bot:/opt/bot
    networks:
      - ticket-test

    depends_on:
      - ticket-bot-mysql
    environment:
      - DISCORD_TOKEN=
      - DB_PROVIDER=
      - DB_CONNECTION_URL=
      - HTTP_EXTERNAL=
      - HTTP_HOST=
      - HTTP_PORT=
      - SETTINGS_PORT=
      - SETTINGS_HOST=
      - SUPER=
      - PUBLIC_BOT=
      - HTTP_TRUST_PROXY=
      - OVERRIDE_ARCHIVE=
      - DISCORD_SECRET=

    restart: unless-stopped

networks:
  ticket-test:

volumes:
  ticket-bot-mysql:
  ticket-bot:
